name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.IMAGE_NAME }} .
        docker tag ${{ secrets.IMAGE_NAME }}:latest ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ secrets.REPOSITORY_NAME }}:latest
        docker push ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ secrets.REPOSITORY_NAME }}:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster ${{ secrets.CLUSTER_NAME }} --service ${{ secrets.SERVICE_NAME }} --force-new-deployment
